---
title: "Converting csv to dataframe"
author: "Philipp Hellwig"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
source("./chess_utils.R")
```

## Load Data

```{r}
rapid_games = read.csv("../data/rapid_games_Dec15final.csv")
```

## Post-error Slowing

Because we are interested in how behaviour is different before a blunder compared to after a blunder, I compute the mean RTs and centipawn losses before and after a blunder:

```{r}
pes = data.frame(matrix(ncol=4, nrow=0))
colnames(pes) = c("pre_rt","pre_cpl","post_rt","post_cpl")

for(user in unique(rapid_games$username)){
  usr_data = subset(rapid_games, username==user)
  pre_rts = numeric()
  pre_cpls = numeric() 
  post_rts = numeric()
  post_cpls = numeric()
  for(i in 1:nrow(usr_data)){
    cpl = csv_list_to_vec(usr_data[i,"cp_losses"], numeric=TRUE)
    times = csv_list_to_vec(usr_data[i,"moveTimes"], numeric=TRUE)
    if(length(cpl) > 3){
      for(index in 2:(length(cpl)-1)){
        if(cpl[index]>199){
          pre_rts = append(pre_rts, times[index-1])
          pre_cpls = append(pre_cpls, cpl[index-1])
          post_rts = append(post_rts, times[index+1])
          post_cpls = append(post_cpls, cpl[index+1])
        }
      }
    }
  }
  pes[user,] = c(
    mean(pre_rts, na.rm=TRUE), 
    mean(pre_cpls, na.rm=TRUE), 
    mean(post_rts, na.rm=TRUE), 
    mean(post_cpls, na.rm=TRUE)
    )
}
```

## T-tests

```{r}
t.test(pes$post_rt, pes$pre_rt, paired=TRUE) # paired t-test for RTs (thinking times)
```

```{r}
t.test(pes$pre_cpl, pes$post_cpl, paired=TRUE) # paired t-test for centipawn losses
```
